# Generated by Django 3.0.8 on 2021-05-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=60)),
                ('email', models.EmailField(db_column='Email', max_length=50, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=15, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=50)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('subject', models.CharField(db_column='Subject', max_length=60, primary_key=True, serialize=False)),
                ('credit_hours', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examid', models.IntegerField(db_column='Examid', primary_key=True, serialize=False)),
                ('pdate', models.DateField(db_column='PDate')),
                ('ptime', models.TimeField(db_column='PTime')),
                ('time_duration', models.IntegerField(db_column='Time_duration')),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='ExamMcqs',
            fields=[
                ('subject', models.CharField(db_column='Subject', max_length=60)),
                ('mquestion', models.CharField(db_column='MQuestion', max_length=250, primary_key=True, serialize=False)),
                ('manswer', models.TextField(db_column='MAnswer')),
                ('point', models.IntegerField(db_column='Point')),
                ('examid', models.ForeignKey(db_column='Examid', on_delete=django.db.models.deletion.CASCADE, to='Database.Exam')),
            ],
            options={
                'db_table': 'exam_mcqs',
                'unique_together': {('mquestion', 'subject', 'examid')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('subject', models.CharField(db_column='Subject', max_length=60)),
                ('question', models.CharField(db_column='Question', max_length=250, primary_key=True, serialize=False)),
                ('keywords', models.CharField(db_column='keywords', max_length=240)),
                ('answer', models.TextField(db_column='Answer')),
                ('point', models.IntegerField(db_column='Point')),
                ('submit', models.BooleanField(db_column='submit', default=True)),
                ('examid', models.ForeignKey(db_column='Examid', on_delete=django.db.models.deletion.CASCADE, to='Database.Exam')),
            ],
            options={
                'db_table': 'exam_questions',
            },
        ),
        migrations.CreateModel(
            name='Mcqs',
            fields=[
                ('subject', models.CharField(db_column='Subject', max_length=60)),
                ('mquestion', models.CharField(db_column='MQuestion', max_length=250, primary_key=True, serialize=False)),
                ('manswer', models.CharField(db_column='MAnswer', max_length=240)),
                ('point', models.IntegerField(db_column='Point')),
                ('mdate', models.DateField(db_column='Mdate')),
            ],
            options={
                'db_table': 'mcqs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=60)),
                ('regno', models.CharField(db_column='RegNo', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('sdate', models.DateField(db_column='SDate')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=60)),
                ('email', models.EmailField(db_column='Email', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=15, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('tdate', models.DateField(db_column='TDate')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='Database.Teacher')),
                ('subject', models.ForeignKey(db_column='Subject', on_delete=django.db.models.deletion.CASCADE, to='Database.Courses')),
            ],
            options={
                'db_table': 'teacher_subject',
            },
        ),
        migrations.CreateModel(
            name='quiz_assignment_id',
            fields=[
                ('uniqueid', models.IntegerField(db_column='Uniqueid', primary_key=True, serialize=False)),
                ('pdate', models.DateField(db_column='PDate')),
                ('req', models.CharField(db_column='Req', max_length=10)),
                ('email', models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='Database.Teacher')),
            ],
            options={
                'db_table': 'quiz_assignment_id',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('subject', models.CharField(db_column='Subject', max_length=60)),
                ('question', models.CharField(db_column='Question', max_length=250, primary_key=True, serialize=False)),
                ('keywords', models.CharField(db_column='keywords', max_length=240)),
                ('answer', models.TextField(db_column='Answer')),
                ('point', models.IntegerField(db_column='Point')),
                ('uniqueid', models.ForeignKey(db_column='Uniqueid', on_delete=django.db.models.deletion.CASCADE, to='Database.quiz_assignment_id')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='McqsChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(db_column='Choice', max_length=300)),
                ('mquestion', models.ForeignKey(db_column='MQuestion', on_delete=django.db.models.deletion.CASCADE, to='Database.Mcqs')),
            ],
            options={
                'db_table': 'mcqs_choice',
            },
        ),
        migrations.AddField(
            model_name='mcqs',
            name='uniqueid',
            field=models.ForeignKey(db_column='Uniqueid', on_delete=django.db.models.deletion.CASCADE, to='Database.quiz_assignment_id'),
        ),
        migrations.CreateModel(
            name='ExamMcqsChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(db_column='Choice', max_length=300)),
                ('mquestion', models.ForeignKey(db_column='MQuestion', on_delete=django.db.models.deletion.CASCADE, to='Database.ExamMcqs')),
            ],
            options={
                'db_table': 'exam__mcqs_choice',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='email',
            field=models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='Database.Teacher'),
        ),
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('message', models.TextField(db_column='Message')),
            ],
            options={
                'db_table': 'ContactUS',
                'unique_together': {('name', 'email', 'message')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.ForeignKey(db_column='RegNo', default='', on_delete=django.db.models.deletion.CASCADE, to='Database.Student')),
                ('subject', models.ForeignKey(db_column='Subject', default='', on_delete=django.db.models.deletion.CASCADE, to='Database.Courses')),
            ],
            options={
                'db_table': 'student_subject',
                'unique_together': {('regno', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentMcqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manswer', models.TextField(db_column='MAnswer')),
                ('mquestion', models.ForeignKey(db_column='MQuestion', on_delete=django.db.models.deletion.CASCADE, to='Database.Mcqs')),
                ('regno', models.ForeignKey(db_column='RegNo', on_delete=django.db.models.deletion.CASCADE, to='Database.Student')),
                ('uniqueid', models.ForeignKey(db_column='Uniqueid', on_delete=django.db.models.deletion.CASCADE, to='Database.quiz_assignment_id')),
            ],
            options={
                'db_table': 'student_mcqs',
                'unique_together': {('regno', 'mquestion', 'uniqueid')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(db_column='Answer')),
                ('question', models.ForeignKey(db_column='Question', on_delete=django.db.models.deletion.CASCADE, to='Database.Questions')),
                ('regno', models.ForeignKey(db_column='RegNo', on_delete=django.db.models.deletion.CASCADE, to='Database.Student')),
                ('uniqueid', models.ForeignKey(db_column='Uniqueid', on_delete=django.db.models.deletion.CASCADE, to='Database.quiz_assignment_id')),
            ],
            options={
                'db_table': 'student_answer',
                'unique_together': {('regno', 'question', 'uniqueid')},
            },
        ),
        migrations.CreateModel(
            name='ResultStubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(db_column='Marks')),
                ('tmarks', models.FloatField(db_column='Total_Marks')),
                ('percentage', models.FloatField(db_column='Percentage')),
                ('Examid', models.ForeignKey(blank=True, db_column='Examid', null=True, on_delete=django.db.models.deletion.CASCADE, to='Database.Exam')),
                ('regno', models.ForeignKey(db_column='RegNo', on_delete=django.db.models.deletion.CASCADE, to='Database.Student')),
                ('subject', models.ForeignKey(db_column='Subject', on_delete=django.db.models.deletion.CASCADE, to='Database.Courses')),
                ('uniqueid', models.ForeignKey(blank=True, db_column='Uniqueid', null=True, on_delete=django.db.models.deletion.CASCADE, to='Database.quiz_assignment_id')),
            ],
            options={
                'db_table': 'result_stubject',
                'unique_together': {('regno', 'subject', 'uniqueid', 'marks'), ('regno', 'subject', 'Examid', 'marks')},
            },
        ),
        migrations.CreateModel(
            name='ExamStudentMcqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manswer', models.TextField(db_column='MAnswer')),
                ('Examid', models.ForeignKey(db_column='Examid', default='null', on_delete=django.db.models.deletion.CASCADE, to='Database.Exam')),
                ('mquestion', models.ForeignKey(db_column='MQuestion', on_delete=django.db.models.deletion.CASCADE, to='Database.ExamMcqs')),
                ('regno', models.ForeignKey(db_column='RegNo', on_delete=django.db.models.deletion.CASCADE, to='Database.Student')),
            ],
            options={
                'db_table': 'exam_student_mcqs',
                'unique_together': {('regno', 'mquestion', 'Examid')},
            },
        ),
        migrations.CreateModel(
            name='ExamStudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(db_column='Answer')),
                ('Examid', models.ForeignKey(db_column='Examid', default='null', on_delete=django.db.models.deletion.CASCADE, to='Database.Exam')),
                ('question', models.ForeignKey(db_column='Question', on_delete=django.db.models.deletion.CASCADE, to='Database.ExamQuestions')),
                ('regno', models.ForeignKey(db_column='RegNo', on_delete=django.db.models.deletion.CASCADE, to='Database.Student')),
            ],
            options={
                'db_table': 'exam_student_answer',
                'unique_together': {('regno', 'question', 'Examid')},
            },
        ),
        migrations.CreateModel(
            name='ExamScanPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(db_column='Answer')),
                ('examid', models.ForeignKey(db_column='Examid', on_delete=django.db.models.deletion.CASCADE, to='Database.Exam')),
                ('question', models.ForeignKey(db_column='Question', on_delete=django.db.models.deletion.CASCADE, to='Database.ExamQuestions')),
                ('regno', models.ForeignKey(db_column='RegNo', on_delete=django.db.models.deletion.CASCADE, to='Database.Student')),
            ],
            options={
                'db_table': 'exam_scan_paper',
                'unique_together': {('regno', 'question', 'examid')},
            },
        ),
    ]
