# Generated by Django 3.0.8 on 2021-04-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.ForeignKey(db_column='Email', on_delete=django.db.models.deletion.DO_NOTHING, to='Database.Admin'),
        ),
        migrations.DeleteModel(
            name='ScanPaper',
        ),
    ]
