# Generated by Django 3.0.8 on 2021-04-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20210420_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(db_column='Email', max_length=50),
        ),
    ]
