# Generated by Django 3.0.8 on 2021-04-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_auto_20210430_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultstubject',
            name='Examid',
            field=models.ForeignKey(db_column='Examid', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Database.Exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultstubject',
            name='tmarks',
            field=models.FloatField(db_column='Total_Marks', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultstubject',
            name='uniqueid',
            field=models.ForeignKey(db_column='Uniqueid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Database.quiz_assignment_id'),
            preserve_default=False,
        ),
    ]
