# Generated by Django 3.0.8 on 2021-04-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_auto_20210430_1059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultstubject',
            unique_together={('regno', 'subject', 'uniqueid', 'Examid', 'marks', 'tmarks', 'percentage')},
        ),
    ]
